# Generated by Django 5.2.1 on 2025-06-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='opportunity',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_type',
            field=models.CharField(choices=[('internship', 'Internship'), ('job', 'Job'), ('grant', 'Grant'), ('scholarship', 'Scholarship'), ('fellowship', 'Fellowship'), ('conference', 'Conference'), ('workshop', 'Workshop'), ('training', 'Training'), ('competition', 'Competition'), ('share_opportunity', 'Share Opportunity'), ('blog', 'Blog'), ('service', 'Service'), ('announcement', 'Announcement'), ('miscellaneous', 'Miscellaneous')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]

