# Generated by Django 5.2.1 on 2025-06-11 23:27

import api.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_opportunity_opportunity_link_opportunity_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advertisements/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='cvreview',
            name='cv_file',
            field=models.FileField(upload_to=api.models.cv_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='mentorrequest',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_requests_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentorrequest',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.opportunity_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='materials',
            field=models.FileField(blank=True, null=True, upload_to=api.models.training_materials_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt', 'pptx', 'zip'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default-profile.png', upload_to=api.models.user_profile_pic_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='materials',
            field=models.FileField(blank=True, null=True, upload_to=api.models.webinar_materials_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt', 'pptx', 'zip'])]),
        ),
        migrations.AlterUniqueTogether(
            name='mentorrequest',
            unique_together={('mentee', 'mentor', 'topic')},
        ),
    ]

