# Generated by Django 5.2.1 on 2025-06-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_adminuser_mentor_education_experience_userdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='short_bio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]

