# Generated by Django 5.2.1 on 2025-06-20 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_short_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityMatchingPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_types', models.JSONField(default=list)),
                ('scholarship_level', models.CharField(blank=True, choices=[('high_school', 'High School'), ('undergraduate', 'Undergraduate'), ('masters', "Master's"), ('phd', 'PhD'), ('postdoc', 'Postdoctoral')], max_length=20, null=True)),
                ('scholarship_types', models.JSONField(default=list)),
                ('scholarship_locations', models.JSONField(default=list)),
                ('job_types', models.JSONField(default=list)),
                ('job_industries', models.CharField(blank=True, max_length=255, null=True)),
                ('internship_types', models.JSONField(default=list)),
                ('internship_fields', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]

