# Generated by Django 5.2.1 on 2025-06-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_opportunitymatchingpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='OpportunityMatchingPreferences',
        ),
    ]

