# Generated by Django 5.2.1 on 2025-06-23 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_communitypost_postcomment_postreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='hidden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='hidden_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]

