# Generated by Django 5.2.1 on 2025-06-26 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_postcomment_parent_comment_commentreaction'),
    ]

    operations = [
    ]

