# Generated by Django 5.2.1 on 2025-06-26 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20250627_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='api.communitypost'),
        ),
    ]

