# Generated by Django 5.2.1 on 2025-06-27 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mentorship_updates'),
        ('api', '0016_user_profile_enhancements'),
    ]

    operations = [
    ]

