# Generated by Django 5.2.1 on 2025-06-28 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_chatroom_call_message_profileactivity_messageread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='organization_logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]

