# Generated by Django 5.2.1 on 2025-07-01 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_communitydiscussion_communitystats_communityreply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]

