# Generated by Django 5.2.1 on 2025-07-02 02:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_delete_adminuser_delete_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('mentorship', '1-on-1 Mentorship'), ('application', 'Application Guidance'), ('interview', 'Interview Preparation'), ('profile', 'Profile Optimization'), ('tips', 'Tips for Success'), ('cv', 'CV/Resume Review'), ('advertisement', 'Advertisement'), ('event', 'Event Promotion')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('people_count', models.PositiveIntegerField(default=1, help_text='Number of people attending')),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=200, null=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='service_files/')),
                ('link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]

