# Generated by Django 4.2.7 on 2025-01-03 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_servicerequest'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS api_blogpost CASCADE;",
            reverse_sql="SELECT 1;"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS api_blogsubmission CASCADE;",
            reverse_sql="SELECT 1;"
        ),
    ]
