# Generated by Django 5.2.1 on 2025-07-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20250703_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='application_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='education',
            name='level',
            field=models.CharField(max_length=20, choices=[('high_school', 'High School'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('certificate', 'Certificate'), ('other', 'Other')], default='bachelor'),
        ),
        migrations.AddField(
            model_name='report',
            name='subject',
            field=models.CharField(max_length=200, default='General Report'),
        ),
        migrations.AddField(
            model_name='interviewpreparation',
            name='tips',
            field=models.TextField(default='General tips'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=200, default='General Feedback'),
        ),
        migrations.AddField(
            model_name='applicationguidance',
            name='category',
            field=models.CharField(max_length=100, default='General'),
        ),
    ]

