# Generated by Django 5.2.1 on 2025-07-03 06:11

from django.db import migrations, models
from ckeditor.fields import RichTextField


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_missing_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='eligibility_criteria',
            field=RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='benefits',
            field=RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='additional_images',
            field=models.JSONField(default=list, blank=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='tags',
            field=models.JSONField(default=list, blank=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='additional_filters',
            field=models.JSONField(default=dict, blank=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='priority_level',
            field=models.IntegerField(default=0),
        ),
    ]

