# Generated by Django 5.2.1 on 2025-07-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_add_truly_missing_columns'),
    ]

    operations = [
    ]

