# Generated by Django 5.2.1 on 2025-07-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_final_missing_columns'),
    ]

    operations = [
    ]

