# Generated by Django 5.2.1 on 2025-07-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_update_opportunity_types'),
    ]

    operations = [
    ]

