# Generated by Django 5.2.1 on 2025-07-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_add_discussion_fk'),
    ]

    operations = [
    ]

