# Generated by Django 5.2.1 on 2025-07-03 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_blogpost_successstory_alter_mentorshipsession_notes_and_more'),
    ]

    operations = [
    ]

