# Generated by Django 5.2.1 on 2025-07-05 13:13

import api.models
import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_fix_mentorship_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TipCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fas fa-lightbulb', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tip Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TipFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=api.models.tip_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.tipcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='call',
            name='caller',
        ),
        migrations.RemoveField(
            model_name='call',
            name='room',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.DeleteModel(
            name='CommunityStats',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='messageread',
            name='message',
        ),
        migrations.AlterUniqueTogether(
            name='messageread',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='messageread',
            name='user',
        ),
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
        migrations.RemoveField(
            model_name='profileactivity',
            name='user',
        ),
        migrations.DeleteModel(
            name='SiteFeedback',
        ),
        migrations.AlterModelOptions(
            name='advertisement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='applicationguidance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='collaborationrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cvreview',
            options={},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-end_date', '-start_date']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-end_date', '-start_date']},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.AlterModelOptions(
            name='interviewpreparation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mentorrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mentorshipsession',
            options={},
        ),
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='profileoptimization',
            options={},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={},
        ),
        migrations.AlterModelOptions(
            name='successstory',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='successtip',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trainingsession',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userdocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='webinar',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='applicationguidance',
            name='author',
        ),
        migrations.RemoveField(
            model_name='applicationguidance',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='applicationguidance',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='collaborationrequest',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='collaborationrequest',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='collaborationrequest',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='communitydiscussion',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='communitypost',
            name='hidden_at',
        ),
        migrations.RemoveField(
            model_name='communitypost',
            name='hidden_by',
        ),
        migrations.RemoveField(
            model_name='communitypost',
            name='hidden_reason',
        ),
        migrations.RemoveField(
            model_name='communitypost',
            name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='communityreply',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cvreview',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cvreview',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='cvreview',
            name='score',
        ),
        migrations.RemoveField(
            model_name='cvreview',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='interviewpreparation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='interviewpreparation',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='interviewpreparation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='mentorrequest',
            name='preferred_date',
        ),
        migrations.RemoveField(
            model_name='mentorrequest',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='mentorrequest',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='mentorshipsession',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='mentorshipsession',
            name='google_meet_link',
        ),
        migrations.RemoveField(
            model_name='mentorshipsession',
            name='meeting_link',
        ),
        migrations.RemoveField(
            model_name='mentorshipsession',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='views',
        ),
        migrations.RemoveField(
            model_name='profileoptimization',
            name='author',
        ),
        migrations.RemoveField(
            model_name='profileoptimization',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='profileoptimization',
            name='updated_at',
        ),


        migrations.RemoveField(
            model_name='report',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='successstory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='successtip',
            name='author',
        ),
        migrations.RemoveField(
            model_name='successtip',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='successtip',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='trainingregistration',
            name='attended',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='meeting_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mentor_availability',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mentor_bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mentor_expertise',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mentor_rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_views',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='recording_link',
        ),
        migrations.RemoveField(
            model_name='webinarregistration',
            name='attended',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='communitydiscussion',
            name='is_anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='communityreply',
            name='is_anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='education',
            name='grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.opportunity_image_path),
        ),
        migrations.AddField(
            model_name='profileoptimization',
            name='platform',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='successstory',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='successtip',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='duration',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='webinar',
            name='duration',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.advertisement_image_path),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='applicationguidance',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='applicationguidance',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='organization_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentreaction',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commentreaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('laugh', 'Laugh'), ('angry', 'Angry'), ('sad', 'Sad')], max_length=10),
        ),
        migrations.AlterField(
            model_name='communitydiscussion',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='content',
            field=models.TextField(default=''),
        ),

        migrations.AlterField(
            model_name='communitypost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.community_post_image_path),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.communitypost'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),

        migrations.AlterField(
            model_name='communityreply',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='cvreview',
            name='additional_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cvreview',
            name='cv_file',
            field=models.FileField(upload_to=api.models.cv_file_path),
        ),
        migrations.AlterField(
            model_name='cvreview',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cvreview',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_reviews_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cvreview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='cvreview',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(choices=[('high_school', 'High School'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('certificate', 'Certificate'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interviewpreparation',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='interviewpreparation',
            name='tips',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='interviewpreparation',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mentorrequest',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentorrequest',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentorrequest',
            name='topic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mentorshipsession',
            name='duration',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='application_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='deadline_type',
            field=models.CharField(choices=[('specific', 'Specific'), ('rolling', 'Rolling'), ('ongoing', 'Ongoing'), ('not_specified', 'Not Specified')], default='specific', max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='opportunity_featured/'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='organization',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='organization_logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos/'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='requirements',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='subtype',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('laugh', 'Laugh'), ('angry', 'Angry'), ('sad', 'Sad')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profileoptimization',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profileoptimization',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('bug', 'Bug Report'), ('content', 'Inappropriate Content'), ('user', 'User Behavior'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='additional_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='contact_info',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='people_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='successtip',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='successtip',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trainingregistration',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trainingsession'),
        ),
        migrations.AlterField(
            model_name='trainingregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.user_profile_pic_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('mentor', 'Mentor'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='short_bio',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='document_type',
            field=models.CharField(choices=[('cv', 'CV/Resume'), ('cover_letter', 'Cover Letter'), ('transcript', 'Academic Transcript'), ('certificate', 'Certificate'), ('portfolio', 'Portfolio'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='file',
            field=models.FileField(upload_to=api.models.user_document_path),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='presenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='webinarregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webinarregistration',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.webinar'),
        ),
        migrations.AddField(
            model_name='tip',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='api.tipcategory'),
        ),
        migrations.DeleteModel(
            name='Call',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageRead',
        ),
        migrations.DeleteModel(
            name='ProfileActivity',
        ),
    ]

