# Generated by Django 5.2.1 on 2025-07-06 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_aboutsection_heroslide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name': 'About Us Section', 'verbose_name_plural': 'About Us Management'},
        ),
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Hero Slide', 'verbose_name_plural': 'About Us - Hero Slides'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Partner', 'verbose_name_plural': 'About Us - Partners'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'About Us - Team Members'},
        ),
        migrations.AddField(
            model_name='heroslide',
            name='about_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='api.aboutsection'),
        ),
        migrations.AddField(
            model_name='partner',
            name='about_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='api.aboutsection'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='about_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='api.aboutsection'),
        ),
    ]

