# Generated by Django 5.2.1 on 2025-07-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_aboutsection_options_alter_heroslide_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='section_type',
            field=models.CharField(choices=[('who_we_are', 'Who We Are'), ('our_mission', 'Our Mission'), ('our_vision', 'Our Vision'), ('founded_in', 'Founded In'), ('what_we_offer', 'What We Offer'), ('our_impact', 'Our Impact')], max_length=50, unique=True),
        ),
    ]

