# Generated by Django 5.2.1 on 2025-07-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_faq_alter_aboutsection_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.TextField(blank=True, default=''),
        ),
    ]

