# Generated by Django 5.2.1 on 2025-07-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='duration',
        ),
        migrations.AddField(
            model_name='mentorrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mentorshipsession',
            name='meeting_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mentorshipsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='mentor_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webinarregistration',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]

