# Generated by Django 5.2.1 on 2025-07-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
