# Generated by Django 5.2.1 on 2025-07-08 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_remove_webinar_duration_mentorrequest_updated_at_and_more'),
        ('api', '0052_auto_20250708_0429'),
    ]

    operations = [
    ]

